reset 33r

diff --git a/package/lean/luci-app-ssr-plus/root/usr/bin/ssr-switch b/package/lean/luci-app-ssr-plus/root/usr/bin/ssr-switch
--- a/package/lean/luci-app-ssr-plus/root/usr/bin/ssr-switch
+++ b/package/lean/luci-app-ssr-plus/root/usr/bin/ssr-switch
@@ -35,27 +35,27 @@ CURRENT_SERVER=$DEFAULT_SERVER
 
 #判断代理是否正常
 check_proxy() {
-local result=0
-local try_count=$(uci_get_by_type global switch_try_count 3)
-for i in $(seq 1 $try_count)
-do
-	/usr/bin/ssr-check www.google.com 80 $switch_time 1
-	if [ "$?" == "0" ]; then
-		# echo "$(date "+%Y-%m-%d %H:%M:%S") Check Google Proxy Success, count=$i" >> /tmp/ssrplus.log
-		result=0
-		break
-	else
-		# echo "$(date "+%Y-%m-%d %H:%M:%S") Check Google Proxy Fail, count=$i" >> /tmp/ssrplus.log
-		/usr/bin/ssr-check www.baidu.com 80 $switch_time 1
-		if [ "$?" == "0" ]; then
-		result=1
-		else
-		result=2
-		fi
-	fi
-	sleep 1;
-	done
-	return $result;
+  local result=0
+  local try_count=$(uci_get_by_type global switch_try_count 3)
+  for i in $(seq 1 $try_count)
+  do
+    /usr/bin/ssr-check www.google.com 80 $switch_time 1
+    if [ "$?" == "0" ]; then
+      # echo "$(date "+%Y-%m-%d %H:%M:%S") Check Google Proxy Success, count=$i" >> /tmp/ssrplus.log
+      result=0
+      break
+    else
+      # echo "$(date "+%Y-%m-%d %H:%M:%S") Check Google Proxy Fail, count=$i" >> /tmp/ssrplus.log
+      /usr/bin/ssr-check www.baidu.com 80 $switch_time 1
+      if [ "$?" == "0" ]; then
+        result=1
+      else
+        result=2
+      fi
+    fi
+    sleep 1;
+  done
+  return $result;
 }
 
 
@@ -126,52 +126,58 @@ start() {
 
 while [ "1" = "1" ]  #死循环
 do
-	sleep $cycle_time
-	LOGTIME=$(date "+%Y-%m-%d %H:%M:%S")
-	#判断当前代理是否为缺省服务器
-	if [ "$CURRENT_SERVER" != "$DEFAULT_SERVER" ] ;then
-	#echo "not default proxy"
-	echo "$(date "+%Y-%m-%d %H:%M:%S") Current server is not default Main server, try to switch back." >> /tmp/ssrplus.log
-	#检查缺省服务器是否正常
-	if test_proxy $DEFAULT_SERVER  ;then
-		#echo "switch to default proxy"
-		echo "$(date "+%Y-%m-%d %H:%M:%S") Main server is avilable." >> /tmp/ssrplus.log
-		#缺省服务器正常，切换回来
-		CURRENT_SERVER=$DEFAULT_SERVER
-		switch_proxy $CURRENT_SERVER
-		echo "$(date "+%Y-%m-%d %H:%M:%S") switch to default ["$(uci_get_by_name $CURRENT_SERVER server)"] proxy!"  >> /tmp/ssrplus.log
-		continue
-	else
-		echo "$(date "+%Y-%m-%d %H:%M:%S") Main server is NOT avilable.Continue using current server." >> /tmp/ssrplus.log
-	fi
-	fi
+   sleep $cycle_time
 
-	#判断当前代理是否正常
-	check_proxy
-	current_ret=$?
+   LOGTIME=$(date "+%Y-%m-%d %H:%M:%S")
 
-	if [ "$current_ret" = "1" ] ;then
-	#当前代理错误，判断有无可用的服务器
-	#echo "current error"
-	echo "$(date "+%Y-%m-%d %H:%M:%S") Current server error, try to switch another server." >> /tmp/ssrplus.log
 
-	select_proxy
-	if [ "$ENABLE_SERVER" != nil ] ;then
-	#有其他服务器可用，进行切换
-	#echo $(uci_get_by_name $new_proxy server)
-	echo "$(date "+%Y-%m-%d %H:%M:%S") Another server is avilable, now switching server." >> /tmp/ssrplus.log
-	CURRENT_SERVER=$ENABLE_SERVER
-	switch_proxy $CURRENT_SERVER
-	normal_flag=1
-	echo "$(date "+%Y-%m-%d %H:%M:%S") ShadowsocksR server switch OK" >> /tmp/ssrplus.log
-	else
-	switch_proxy $CURRENT_SERVER
-	normal_flag=1
-	echo "$(date "+%Y-%m-%d %H:%M:%S") Try restart current server." >> /tmp/ssrplus.log
-	fi
-	else
-	normal_flag=0
-	echo "$(date "+%Y-%m-%d %H:%M:%S") ShadowsocksR No Problem."  >> /tmp/ssrplus.log
-	fi
+   #判断当前代理是否为缺省服务器
+   if [ "$CURRENT_SERVER" != "$DEFAULT_SERVER" ] ;then
+   #echo "not default proxy"
+   echo "$(date "+%Y-%m-%d %H:%M:%S") Current server is not default Main server, try to switch back." >> /tmp/ssrplus.log
+
+     #检查缺省服务器是否正常
+     if test_proxy $DEFAULT_SERVER  ;then
+       #echo "switch to default proxy"
+       echo "$(date "+%Y-%m-%d %H:%M:%S") Main server is avilable." >> /tmp/ssrplus.log
+       #缺省服务器正常，切换回来
+       CURRENT_SERVER=$DEFAULT_SERVER
+       switch_proxy $CURRENT_SERVER
+       echo "$(date "+%Y-%m-%d %H:%M:%S") switch to default ["$(uci_get_by_name $CURRENT_SERVER server)"] proxy!"  >> /tmp/ssrplus.log
+       continue
+     else
+       echo "$(date "+%Y-%m-%d %H:%M:%S") Main server is NOT avilable.Continue using current server." >> /tmp/ssrplus.log
+     fi
+    fi
+
+   #判断当前代理是否正常
+   check_proxy
+   current_ret=$?
+
+   if [ "$current_ret" = "1" ] ;then
+     #当前代理错误，判断有无可用的服务器
+     #echo "current error"
+     echo "$(date "+%Y-%m-%d %H:%M:%S") Current server error, try to switch another server." >> /tmp/ssrplus.log
+
+     select_proxy
+     if [ "$ENABLE_SERVER" != nil ] ;then
+      #有其他服务器可用，进行切换
+      #echo $(uci_get_by_name $new_proxy server)
+      echo "$(date "+%Y-%m-%d %H:%M:%S") Another server is avilable, now switching server." >> /tmp/ssrplus.log
+      CURRENT_SERVER=$ENABLE_SERVER
+      switch_proxy $CURRENT_SERVER
+      normal_flag=1
+      echo "$(date "+%Y-%m-%d %H:%M:%S") ShadowsocksR server switch OK" >> /tmp/ssrplus.log
+     else
+      switch_proxy $CURRENT_SERVER
+      normal_flag=1
+      echo "$(date "+%Y-%m-%d %H:%M:%S") Try restart current server." >> /tmp/ssrplus.log
+     fi
+   else
+    normal_flag=0
+    echo "$(date "+%Y-%m-%d %H:%M:%S") ShadowsocksR No Problem."  >> /tmp/ssrplus.log
+   fi
+
+
 done
 }
